---
title: "Journal 1"
author: "Bogdan Cuza"
---

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r format(Sys.time(), '%B, %Y')`

<br>

------------------------------------------------------------------------

# Lab 1 Handling social network data in R

------------------------------------------------------------------------

Loading packages:
```{r}
library(network)
library(igraph)
library(reshape2)
library(tidyverse)
```

Loading data:
```{r}
url1 <- "https://github.com/rensec/sasr08/raw/main/g_adj_matrix_simple.csv"
g_matrix <- read.csv(file = url1, header = FALSE)
g_matrix
```

Convert to matrix:
```{r}
g_matrix <- as.matrix(g_matrix)
g_matrix
```

```{r}
rownames(g_matrix) <- 1:nrow(g_matrix)
colnames(g_matrix) <- 1:ncol(g_matrix)
g_matrix
```

**ANSWER**: There are 5 nodes, and 4 edges.

Retrieve additional information
```{r}
g_nodes_age <- read.csv(file = "https://github.com/rensec/sasr08/raw/main/g_nodes_age.csv")
g_nodes_age
```

Convert to igraph object:
```{r}
g <- graph_from_adjacency_matrix(g_matrix)
class(g)
g
```

Add attributes and plot:
```{r}
g <- set_vertex_attr(g, 
                     name = "age",
                     value = g_nodes_age$age)
plot(g)
```

Also with edge list:
```{r}
g_elist <- read.csv(file = "https://github.com/rensec/sasr08/raw/main/g_elist.csv")
g_elist
g_from_elist <- graph_from_data_frame(g_elist) 
plot(g_from_elist)
```

**NOTE**: must includde isolate

```{r}
g_from_elist <- graph_from_data_frame(g_elist, vertices = g_nodes_age) 
plot(g_from_elist)
```